config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :theatres
  root 'home#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :movies
  resources :theaters do
    resources :bookings
  end
end

app/models/theatre.rb
class Theatre < ApplicationRecord
  belongs_to :movie
end

app/controllers/theatres_controller.rb
class TheatresController < ApplicationController
  before_action :set_theatre, only: [:show, :edit, :update, :destroy]

  # GET /theatres
  # GET /theatres.json
  def index
    @theatres = Theatre.all
  end

  # GET /theatres/1
  # GET /theatres/1.json
  def show
  end

  # GET /theatres/new
  def new
    @theatre = Theatre.new
  end

  # GET /theatres/1/edit
  def edit
  end

  # POST /theatres
  # POST /theatres.json
  def create
    @theatre = Theatre.new(theatre_params)

    respond_to do |format|
      if @theatre.save
        format.html { redirect_to @theatre, notice: 'Theatre was successfully created.' }
        format.json { render :show, status: :created, location: @theatre }
      else
        format.html { render :new }
        format.json { render json: @theatre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /theatres/1
  # PATCH/PUT /theatres/1.json
  def update
    respond_to do |format|
      if @theatre.update(theatre_params)
        format.html { redirect_to @theatre, notice: 'Theatre was successfully updated.' }
        format.json { render :show, status: :ok, location: @theatre }
      else
        format.html { render :edit }
        format.json { render json: @theatre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theatres/1
  # DELETE /theatres/1.json
  def destroy
    @theatre.destroy
    respond_to do |format|
      format.html { redirect_to theatres_url, notice: 'Theatre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theatre
      @theatre = Theatre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def theatre_params
      params.require(:theatre).permit(:t_name, :place)
    end
end

app/helpers/theatres_helper.rb
module TheatresHelper
end

app/views/theatres/_form.html.erb
<%= form_with(model: theatre, local: true) do |form| %>
  <% if theatre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(theatre.errors.count, "error") %> prohibited this theatre from being saved:</h2>

      <ul>
        <% theatre.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :t_name %>
    <%= form.text_field :t_name %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/theatres/edit.html.erb
<h1>Editing Theatre</h1>

<%= render 'form', theatre: @theatre %>

<%= link_to 'Show', @theatre %> |
<%= link_to 'Back', theatres_path %>

app/views/theatres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Theatres</h1>

<table>
  <thead>
    <tr>
      <th>T name</th>
      <th>Place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @theatres.each do |theatre| %>
      <tr>
        <td><%= theatre.t_name %></td>
        <td><%= theatre.place %></td>
        <td><%= link_to 'Show', theatre %></td>
        <td><%= link_to 'Edit', edit_theatre_path(theatre) %></td>
        <td><%= link_to 'Destroy', theatre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Book Tickets', new_booking_path %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Theatre', new_theatre_path %>

app/views/theatres/new.html.erb
<h1>New Theatre</h1>

<%= render 'form', theatre: @theatre %>

<%= link_to 'Back', theatres_path %>

app/views/theatres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>T name:</strong>
  <%= @theatre.t_name %>
</p>

<p>
  <strong>Place:</strong>
  <%= @theatre.place %>
</p>

<%= link_to 'Edit', edit_theatre_path(@theatre) %> |
<%= link_to 'Back', theatres_path %>