config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :theatres
  root 'home#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :movies
  resources :theaters do
    resources :bookings
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  # belongs_to :users
  # validates :tickets_required, format: { with: /(?:[1-7]|0[1-7]|)/i, message:  "Upto 7 tickets only can be booked" }
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        BookingmailerMailer.welcome_mail(@booking).deliver_later
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:user_mail, :phone_number,  :seat_number,:seat_number1,
        :seat_number2,:seat_number3,:seat_number4,:seat_number5,:seat_number6,:seat_number7,:seat_number8,:seat_number9, :location)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_mail %>
    <%= form.text_field :user_mail %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>


  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :seat_number %>
    <%= form.select :seat_number, options_for_select(0..500)%>
  </div>

  <div class="field">
    <%= form.label :seat_number %>
    <%= form.select :seat_number1, options_for_select(0..500)%>
  </div>

  <div class="field">
    <%= form.label :seat_number %>
    <%= form.select :seat_number2, options_for_select(0..500)%>
  </div>

  <div class="field">
    <%= form.label :seat_number %>
    <%= form.select :seat_number3, options_for_select(0..500)%>
  </div>

  <div class="field">
    <%= form.label :seat_number %>
    <%= form.select :seat_number4, options_for_select(0..500)%>
  </div>

  <div class="field">
    <%= form.label :seat_number %>
    <%= form.select :seat_number5, options_for_select(0..500)%>
  </div>

  <div class="field">
    <%= form.label :seat_number %>
    <%= form.select :seat_number6, options_for_select(0..500)%>
  </div>

  <div class="field">
    <%= form.label :seat_number %>
    <%= form.select :seat_number7, options_for_select(0..500)%>
  </div>

  <div class="field">
    <%= form.label :seat_number %>
    <%= form.select :seat_number8, options_for_select(0..500)%>
  </div>

  <div class="field">
    <%= form.label :seat_number %>
    <%= form.select :seat_number9, options_for_select(0..500)%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>user_mail</th>
      <th>Phone number</th>
      <th>Tickets required</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.user_mail %></td>
        <td><%= booking.phone_number %></td>
        <td><%= booking.seat_number %></td>
        <td><%= booking.seat_number1 %></td>
        <td><%= booking.seat_number2 %></td>
        <td><%= booking.seat_number3 %></td>
        <td><%= booking.seat_number4 %></td>
        <td><%= booking.seat_number5 %></td>
        <td><%= booking.seat_number6 %></td>
        <td><%= booking.seat_number7 %></td>
        <td><%= booking.seat_number8 %></td>
        <td><%= booking.seat_number9 %></td>
        <td><%= booking.location %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>user_mail:</strong>
  <%= @booking.user_mail %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @booking.phone_number %>
</p>

<p>
  <strong>Location:</strong>
  <%= @booking.location %>
</p>

<p>
  <strong>Selected Seat Numbers:</strong>
  <%= @booking.seat_number %>
</p>

<p>
  <strong>Selected Seat Numbers:</strong>
  <%= @booking.seat_number1 %>
</p>

<p>
  <strong>Selected Seat Numbers:</strong>
  <%= @booking.seat_number2 %>
</p>

<p>
  <strong>Selected Seat Numbers:</strong>
  <%= @booking.seat_number3 %>
</p>

<p>
  <strong>Selected Seat Numbers:</strong>
  <%= @booking.seat_number %>
</p>

<p>
  <strong>Selected Seat Numbers:</strong>
  <%= @booking.seat_number4 %>
</p>

<p>
  <strong>Selected Seat Numbers:</strong>
  <%= @booking.seat_number5 %>
</p>

<p>
  <strong>Selected Seat Numbers:</strong>
  <%= @booking.seat_number6 %>
</p>

<p>
  <strong>Selected Seat Numbers:</strong>
  <%= @booking.seat_number7 %>
</p>

<p>
  <strong>Selected Seat Nu8bers:</strong>
  <%= @booking.seat_number7 %>
</p>

<p>
  <strong>Selected Seat Numbers:</strong>
  <%= @booking.seat_number9 %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>